### ISSUE TITLE
WebRTCModule/GetUserMediaImpl.java videoConstraintsMandatory : Null pointer exception

### ISSUE THREAD

**Issue by saket424** [atyenoria/react-native-webrtc-janus-gateway#3]
@atyenoria ,
I encountered a null pointer exception when I tried to run the Android sample with videoConstraintsMandatory in react-native-janus-gateway-webrtc-video-chat/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/GetUserMediaImpl.java

When I changed the code from

            // Fall back to defaults if keys are missing.
            int width
                    = videoConstraintsMandatory.hasKey("minWidth")
                    ? videoConstraintsMandatory.getInt("minWidth")
                    : DEFAULT_WIDTH;
            int height
                    = videoConstraintsMandatory.hasKey("minHeight")
                    ? videoConstraintsMandatory.getInt("minHeight")
                    : DEFAULT_HEIGHT;
            int fps
                    = videoConstraintsMandatory.hasKey("minFrameRate")
                    ? videoConstraintsMandatory.getInt("minFrameRate")
                    : DEFAULT_FPS;

to this instead

        int width, height, fps;
        // Fall back to defaults if keys are missing.
        if (videoConstraintsMandatory != null) {
             width
                    = videoConstraintsMandatory.hasKey("minWidth")
                    ? videoConstraintsMandatory.getInt("minWidth")
                    : DEFAULT_WIDTH;
            height
                    = videoConstraintsMandatory.hasKey("minHeight")
                    ? videoConstraintsMandatory.getInt("minHeight")
                    : DEFAULT_HEIGHT;
            fps
                    = videoConstraintsMandatory.hasKey("minFrameRate")
                    ? videoConstraintsMandatory.getInt("minFrameRate")
                    : DEFAULT_FPS;
        } else {
            width = DEFAULT_WIDTH;
            height = DEFAULT_HEIGHT;
            fps = DEFAULT_FPS;
        }

then the react-native-janus-gateway-webrtc-video-chat VideoRoom sample worked. Did you encounter a similar issue and if yes, what is the proposed work around? I know you state that android is still a work in progress but I was impatient and wanted to give it a whirl

Thanks

**Comment by atyenoria** [comment]
Thanks for creating the issue. 
@saket424 
I could't start InCallManager.start({ media: 'audio' }) with react-native-incall manager. 
Other part works. But, I am not familiar with the error you raised above. 
Are you trying this in real Android device?
I used the Android Studio emulator when I came across the problem.

**Comment by saket424** [comment]
Yes I tried on a real Android device

**Comment by reedspool** [comment]
+1 Had same issue, @saket424's solution worked for me as well

**Comment by atyenoria** [comment]
@caseygbigelow
Nice! That patch seems to prevent app from crashing!!
