### ISSUE TITLE
build fail in xcode 9.1

### ISSUE THREAD

**Issue by qengli** [atyenoria/react-native-webrtc-janus-gateway#4]
![image](https://user-images.githubusercontent.com/320935/33515777-318dafd8-d7a2-11e7-9d98-20b00b5b00b8.png)

**Comment by atyenoria** [comment]
Thanks for trying this repo!
It seems to be the react-native related bug, not the react-native-webrtc.
Did you set up the node path like README.md?
And, Are you killing all process working for other react-native project before trying?
