### ISSUE TITLE
Janus streaming not work

### ISSUE THREAD

**Issue by NatChung** [atyenoria/react-native-webrtc-janus-gateway#5]
Hi 
I am using Janus gateway to streaming RTP to RTCView, but it only works in rn-less-40, like this sample: https://github.com/inspiraluna/JanusReact, but when I switch the newest version (1.58.3) , it doesn't work and doesn't show any error message

**Comment by atyenoria** [comment]
I don't know why that happens.
Can you try the streaming plugin by modifying this repo?

**Comment by NatChung** [comment]
Thanks for your reply, I fixed the problem. the problem in Android is an H264 codec issue, Each time streaming coming, the Android logcat shows codec been released, therefore I can't see any video on the screen. So I copy the older version webrtc.framework and webrtc.jar to iOS and Android and it works(Need to fixed some compile issue). for some reason, I can't use old react-native

**Comment by atyenoria** [comment]
Great. Thank you for the info.
